### ISSUE TITLE
Concept page layout malformities

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Skosmos#1006]
## At which URL did you encounter the problem?
https://finto.fi/koko/fi/page/p12885?clang=en

Two issues: 

1. Property names are not in line with property values horizontally
2. There is a larger gap above a property value than below

See picture below:

![image](https://user-images.githubusercontent.com/8804680/84886698-6e978800-b09d-11ea-8d5f-d99dfd6e1768.png)

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox 68.9.0esr (64-bit)

**Comment by kinow** [comment]
I think that's because the left column text was much longer than the right column text. The text on the left has the default word break value, causing it to break word, on the first word.

![image](https://user-images.githubusercontent.com/304786/84890998-4d5f8780-b0ef-11ea-8c8f-76d95d9ef0c4.png)

With `word-break: all` I think it looks a bit better.

![image](https://user-images.githubusercontent.com/304786/84891067-6831fc00-b0ef-11ea-947c-3a3ac1510c58.png)

The left `<div>` ends up with a height greater than the right `<div>`. So the elements are still misaligned. SKOSMOS is using Bootstrap 3. So the grid elements for row and columns are not flex.

![image](https://user-images.githubusercontent.com/304786/84891337-cf4fb080-b0ef-11ea-974e-452a516732c1.png)

So it is really tricky to dimension the elements purely with CSS, without any JS. And quite easy for things to get messy (probably one of the reasons why flexbox was created).

Bootstrap 4's grid layout was created with flexbox, and most browsers support it. Bootstrap 5 alpha is out too I think (probably a few days ago?). So updating to Bootstrap 4 might either fix it, or make things easier in the layout of SKOSMOS UI.

Here's what it looks like by setting the rows to be `flex`, and `flex-direction: row`, and the columns similarly with a column direction. And with some stretch. All done quickly in the Firefox developer tools.

![image](https://user-images.githubusercontent.com/304786/84891557-2fdeed80-b0f0-11ea-993d-7c8384521835.png)

This way the browser is instructed that the elements are rows and columns, and that we would like them to be stretched to its maximum height/widget. Causing the borders to appear in the right places.

Not sure if worth fixing it with the current CSS, or if it would be easier to do that after updating to a more recent Bootstrap version (so that the changes don't get discarded after an update later).

Bruno

**Comment by osma** [comment]
Thanks for your analysis @kinow! I agree 100% that the best solution is to upgrade to Bootstrap 4. I've used it in other projects (e.g. Finto AI, annif.org) and it's really nice to work with.

**Comment by kouralex** [comment]
The first issue here has already been reported in #745 and was fixed in #1067
The second issue was fixed by @joelit in #1055
