### ISSUE TITLE
Change wording of note for deprecated concepts

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1181]
## At which URL did you encounter the problem?
http://finto.fi/cn/en/page/63141A
http://finto.fi/cn/fi/page/63141A

## What steps will reproduce the problem?
1. Go to above URL
2. Look at the text in the red box

## What is the expected output? What do you see instead?

The text says "This concept has been deprecated. Do not use this concept for annotation!"
or in Finnish "Käsite on poistettu käytöstä. Älä käytä tätä käsitettä sisällönkuvailuun!"

The text is a bit confusing since it's debatable whether this concept (really a corporate name / entity) was primarily intended for annotation / subject indexing even when it was still valid. The suggestion is to change the text to simply drop the last part, i.e. 

"This concept has been deprecated. Do not use this concept!"
"Käsite on poistettu käytöstä. Älä käytä tätä käsitettä!"

The change itself is really small, but changing the English expression affects all the translations on Transifex, so they need to be synchronized as well.

(in Swedish the equivalent expressionis "Begreppet har tagits ur bruk." which does not have this problem)

Change requested by Katerina S.

**Comment by fantsby-m** [comment]
This will later be relevant in Metatietosanasto (MTS, Metadata Thesaurus) as well, and the current formulation _Käsite on poistettu käytöstä. Älä käytä tätä käsitettä sisällönkuvailuun!_ is not applicable there, since MTS is not used in subject cataloging/indexing (=sisällönkuvailu). An alternative new formulation could be _Käsite on poistettu käytöstä. Älä käytä tätä käsitettä kuvailussa!_ - which would broaden the meaning from mere subject indexing.

**Comment by ksornova** [comment]
Tämä olisi hyödyllinen muutos paitsi Kanton, niin myös Metatietosanaston näkökulmasta. Metatietosanastossa ei tosin vielä pysty deprikoimaan termejä, mutta sitten kun pystyy, niin samaa ilmoitusta tarvitaan sinnekin.
