### ISSUE TITLE
Autocomplete component does not highlight the search term as a matching part when using decomposed unicode characters

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1246]
## At which URL did you encounter the problem?

* Create a **decomposed** search term version of some search term that contains **precomposed** special characters, for example:
This could be reproduced by creating a decomposed unicode search string, for example in linux terminal:
`uconv -x any-nfd <<<'Etholén, Hans'`
 * Precomposed `Etholén, Hans` that escapes as Ethol**%C3%A9**n%2C+Hans
 * And decomposed 'Etholén, Hans' that escapes as Ethol**e%CC%81**n%2C+Hans

## What steps will reproduce the problem?
1. Navigate to a vocabulary containing a concept matching your search term
2. Search with the decomposed version in the upper-right reach field
3. Compare it to searching with the precomposed version in the upper-right reach field

## What is the expected output? What do you see instead?
![image](https://user-images.githubusercontent.com/578627/141253385-0b90622e-61b9-4216-a102-6cb92ee4ac7d.png)

It seems that the highlighting of a matching term does not work in `typeahead.js` for decomposed unicode characters. Also discussed in #1184 and #1239 .

**Comment by osma** [comment]
This is very similar to issue #423, which was already closed because it's very hard to fix.

I don't think we should even try to support decomposed Unicode characters. [RDF 1.1 Concepts and Abstract Syntax section 3.3 Literals](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal) says that string literals have a:

> lexical form, being a Unicode [[UNICODE](https://www.w3.org/TR/rdf11-concepts/#bib-UNICODE)] string, which SHOULD be in Normal Form C [[NFC](https://www.w3.org/TR/rdf11-concepts/#bib-NFC)],

If the RDF data Skosmos is given doesn't follow that recommendation, there isn't much we can do. It will cause many other problems, much more severe than lack of highlighting.

Closing this issue, but feel free to reopen it if there are good arguments for reconsidering, especially specific data sets that need to be supported.
