### ISSUE TITLE
Default value columns for vocabulary-specific configuration table needed on the Skosmos Wiki-pages 

### ISSUE THREAD

**Issue by miguelvaara** [NatLibFi/Skosmos#1255]
Follow the way presented in the Global configuration section (_Default value if not set_) on the page https://github.com/NatLibFi/Skosmos/wiki/Configuration

**Comment by osma** [comment]
@miguelvaara has been adding default values to the table. I reviewed them and made some [changes](https://github.com/NatLibFi/Skosmos/wiki/Configuration/_compare/22e056808e15bf05f0472ac08c84f6caa6d6fff6...bc2657a0b0ebea19f0c044c43ce87b836d906b83) directly into the wiki, because there is no PR mechanism for wiki edits.

I changed a lot of `null` values into `(unset)` or something more appropriate for the context of Turtle configuration, where `null` is not meaningful.

I think we are done with this, so closing the issue. Please reopen if necessary - or for minor tweaks, just edit the wiki page directly.
