### ISSUE TITLE
Fix plugins that were broken in the Bootstrap upgrade

### ISSUE THREAD

**Issue by miguelvaara** [NatLibFi/Skosmos#1306]
## At which URL did you encounter the problem?
https://dev.finto.fi/finaf/fi/page/000000515
https://dev.finto.fi/yso/fi/page/p18776
.. and likely in many other URLs related to the vocabularies maintained with Skosmos using the latest master branch and including the Bootstrap 5 updates.

## Which steps will reproduce the problem?
1. In your own local Skosmos installation, configure and take into use at least the following plugins:
- Finna
- Map
- Message
- Finaf
- Wikipedia
(it may be needed to go through other plugins as well)
2. Make sure that you have pulled the latest master branch. 
3. Run: _php composer.phar self-update_
4. Run: _php composer.phar update_
5. Create a new branch for the testing.
6. Visually inspect the appearance and functionalities of the plugins to find possible issues.
7. Check the next PR including the Bootstrap upgrades: https://github.com/NatLibFi/Skosmos/pull/1182

Help for the steps 3-4: https://github.com/NatLibFi/Skosmos/wiki/Upgrading

## What is the expected output? What do you see instead?
Correctly working plugins / Broken layouts

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by kinow** [comment]
Whoever works on this, feel free to ping me if you need any help :+1:

**Comment by miguelvaara** [comment]
This is what we have now (co-operation with @Vainonen & @miguelvaara):
https://github.com/NatLibFi/skosmos-widget-finaf/compare/bootstrap-update

It is not much but a beginning. After working together @miguelvaara tried to setup Finaf (Kanto) vocabulary in his own development environment. Maybe the most mysterious 🤔 part is that everything seems to be fine on the code side and in the DOM but the Finaf widget remains hidden. 

Maybe @Vainonen provides some tips later on .. 🙂

**Comment by miguelvaara** [comment]
Next in line: Finna widget https://github.com/NatLibFi/Skosmos-widget-finna/issues/11

**Comment by kinow** [comment]
>This is what we have now (co-operation with @Vainonen & @miguelvaara):
https://github.com/NatLibFi/skosmos-widget-finaf/compare/bootstrap-update

Applied that [diff](https://github.com/NatLibFi/skosmos-widget-finaf/compare/bootstrap-update.diff) locally, after copying the [finaf vocab settings](https://github.com/NatLibFi/Finto-data/blob/master/conf/finto.fi/config.ttl), and accessing finto.fi to compare with my local installation.

Here's the current broken plugin page:

![image](https://user-images.githubusercontent.com/304786/165504107-9f2e56d8-3876-4773-8288-9f25d4d3cb9b.png)

Here's after applying the diff.

![image](https://user-images.githubusercontent.com/304786/165504910-97ba3eec-b9bd-4b0a-a285-df7c22fa926c.png)

Here's Finto:

![image](https://user-images.githubusercontent.com/304786/165505352-a5cc93a1-0a2b-452d-96c0-55c02023764b.png)

>It is not much but a beginning. After working together @miguelvaara tried to setup Finaf (Kanto) vocabulary in his own development environment. Maybe the most mysterious thinking part is that everything seems to be fine on the code side and in the DOM but the Finaf widget remains hidden.

In case it helps, here's what I did @miguelvaara :

1. Cloned the plugin to `skosmos-clone/plugins/finaf`
2. After installing Finaf as in Finto, I made sure I had `skosmos:usePlugin "finaf" ;`
3. Opened a URL from Finto, e.g. https://finto.fi/finaf/en/page/000001172?clang=fi, locally to compare the results http://localhost:9090/finaf/en/page/000001172?clang=fi (with Docker Compose)

I think the diff is fixing most of the Bootstrap mayhem, except for the icons. @osma, I think we had a similar issue in the Bootstrap issue, where I [used a SVG](https://github.com/NatLibFi/Skosmos/blob/master/resource/pics/clipboard.svg) since Bootstrap removed its icons.

If needed, we can open a new issue to add back the icons via an alternative dependency (Bootstrap website should list a few alternatives). This way the finaf plug-in can also be updated to show the icons correctly.

Other than that, looks good to me! Great job @Vainonen & @miguelvaara :bow:

**Comment by joelit** [comment]
I added pull requests to Skosmos-widget-map and Skosmos-wdget-wiki with their respective fixes for Bootstrap 5
* [Map plugin PR](https://github.com/NatLibFi/Skosmos-widget-map/pull/1)
* [Wiki plugin PR (draft)](https://github.com/NatLibFi/Skosmos-widget-wiki/pull/7)

**Comment by osma** [comment]
I think we are done (for now) with this? Anyway, the issues should be handled in the repos of individual widgets rather than this Skosmos repo, which is really about the Skosmos codebase and not the widgets.
