### ISSUE TITLE
Vocabulary information is missing from the drop-down results list

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1323]
## At which URL did you encounter the problem?
At the vocabularies list, front page, e.g. dev.finto.fi

## What steps will reproduce the problem?
1. At the search bar, make sure that "from all" is checked in the source vocabulary list
2. Type a search term and wait for autocomplete to show the search results
3. The source vocabulary information is missing from the result drop-down list

## What is the expected output? What do you see instead?
There should be information of the source vocabulary for each search result.

A list of results with no source information means it is not possible to differentiate between the results with same preferred labels.
![Screenshot from 2022-05-17 10-49-44](https://user-images.githubusercontent.com/578627/168786546-0e36cfc6-d263-488d-b596-af492a8b3dad.png)

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox & Chrome

**Comment by osma** [comment]
For reference, here is the same view from Finto.fi (which is running Skosmos 2.14):

![kuva](https://user-images.githubusercontent.com/1132830/171380675-16b78875-f6bb-4f54-bde9-f705f4084eda.png)

Note the names of the vocabularies (Iconclass, AFO etc.).
Also, the concept types are shown in a dark color instead of the blueish link color.
