### ISSUE TITLE
Namespace prefix configuration for Skosmos

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1344]
The current state of managing the RDF NS prefixes in Skosmos could be improved.

## At which URL did you encounter the problem?
https://finto.fi/rest/v1/yso/data?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp1191&format=text/turtle

## What is the expected output? What do you see instead?
I would expect to see commonly used prefixes, like:
```
@prefix yso: <http://www.yso.fi/onto/yso/> .
@prefix ysometa: <http://www.yso.fi/onto/yso-meta/> .
@prefix dct: <http://purl.org/dc/terms/> .
```

But what we get is:
```
@prefix ysoaika: <http://www.yso.fi/onto/yso/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix koko: <http://www.yso.fi/onto/koko/> .
@prefix allars: <http://www.yso.fi/onto/allars/> .
@prefix ysa: <http://www.yso.fi/onto/ysa/> .
@prefix ns0: <http://www.yso.fi/onto/yso-meta/> .
@prefix dc: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix isothes: <http://purl.org/iso25964/skos-thes#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
```
yso -> ysoaika : this prefix does not come from the currently viewed vocabulary, but it would make sense in yso-aika vocabulary, where this prefix likely originates from. Should the prefix definitions leak from one vocabulay to another?

ysometa -> ns0 : this prefix must have been set in the vocabulary data, but for some reason it gets anonymized. Should prefixes get dropped like this?

dct -> dc : some commonly used urispaces could be centrally configured in a way that overrides local uses of the prefix

The prefixes do not break anything in the RDF data, as the reasoning is conducted using the full uris, but:
 * This does create some confusion from users
 * This does break Skosmos transaltion components which assume a certain NS prefix for a shortened URI used as a translation key

**Comment by osma** [comment]
There is some confusion here about the origin of namespace prefixes. They do *not* come from vocabulary data. Skosmos doesn't 'see' the prefixes used in vocabulary data files directly, as they are stored in Fuseki. Fuseki has its own logic in how it stores prefixes and I don't know exactly how that works, but the important point is that they are not segmented by vocabulary (graph in Fuseki).

What Skosmos does instead is this:

1. Some namespace prefixes are [preregistered by EasyRdf](https://github.com/easyrdf/easyrdf/blob/main/lib/RdfNamespace.php#L56). These include common ones like `rdf`, `rdfs`, `dc` (meaning DCTerms), `dc11` (original DC 1.1), `skos` etc.
2. More specific namespaces (e.g. `skosmos`, `isothes`, `wd`...) are [registered by Skosmos](https://github.com/NatLibFi/Skosmos/blob/master/model/GlobalConfig.php#L6-L13)
3. The namespace prefixes defined in `config.ttl` are also [registered by Skosmos](https://github.com/NatLibFi/Skosmos/blob/master/model/GlobalConfig.php#L126-L135).
4. The vocabulary IDs used in `config.ttl`, along with their URI namespaces, are also [registered by Skosmos](https://github.com/NatLibFi/Skosmos/blob/master/model/Model.php#L350-L360).

> yso -> ysoaika : this prefix does not come from the currently viewed vocabulary, but it would make sense in yso-aika vocabulary, where this prefix likely originates from. Should the prefix definitions leak from one vocabulay to another?

This most likely originates from step 4 above. The vocabulary `yso-aika` appears before `yso` in the configuration file and both have the same URI space. So it gets used as a namespace prefix (stripping the hyphen), and grabs the YSO namespace. There are two possible fixes:

1. Set the YSO namespace prefix in `config.ttl`. This way it gets assigned already in step 3, so it cannot be grabbed later by `yso-aika`. This is IMO the preferred way to fix this particular problem.
2. Move the declaration of `yso-aika` vocabulary so it comes after `yso` in `config.ttl`. Since EasyRdf parses the file in order, this would give the `yso` vocabulary a chance to grab the `yso:` prefix. This would be a good idea to do anyway, because currently `yso-aika` violates the alphabetical order of vocabularies in the `config.ttl` file that Finto uses.

> ysometa -> ns0 : this prefix must have been set in the vocabulary data, but for some reason it gets anonymized. Should prefixes get dropped like this?

Again, Skosmos doesn't "see" the vocabulary prefixes used in vocabulary data. To avoid introducing prefixes like `ns0`, it would be best to declare this prefix in `config.ttl`.

> dct -> dc : some commonly used urispaces could be centrally configured in a way that overrides local uses of the prefix

This comes from the EasyRdf preassigned prefixes (step 1 above). For some reason, they chose `dc` for DCTerms and `dc11` for DC Elements 1.1, while in other contexts `dc` is often used for DC Elements and `dct` for DCTerms. It would be possible to redeclare these prefixes in Skosmos code if we're unhappy with the choices made by EasyRdf.

> This does break Skosmos transaltion components which assume a certain NS prefix for a shortened URI used as a translation key

Do you have an example of this breakage? In my understanding, the translations only refer to prefixes registered by either EasyRdf (step 1) or Skosmos (step 2), so there should be no mismatch.

**Comment by joelit** [comment]
> > This does break Skosmos transaltion components which assume a certain NS prefix for a shortened URI used as a translation key
> 
> Do you have an example of this breakage? In my understanding, the translations only refer to hardcoded prefixes registered by either EasyRdf (step 1) or Skosmos (step 2), so there should be no mismatch.

This seems to be an example of dc11 showing instead of dc. But you are right, it could also be a result of using dc-elements instead of the newer dc-terms ns of the source property, as the property exists in both namespaces:

![Screenshot from 2022-08-23 15-57-15](https://user-images.githubusercontent.com/578627/188104697-e078e091-23a0-44fe-83b4-6cf0a3db6781.png)

**Comment by osma** [comment]
There is some code in Vocabulary.php that tries to normalize DC namespace prefixes so that the correct labels can be found regardless of which DC prefix has been used: https://github.com/NatLibFi/Skosmos/blob/14d24cd26395d9b1d62ed36f6c9dc4337a1faba9/model/Vocabulary.php#L193-L206

(see lines 193, 198 and 206 above)

But apparently this only applies to properties on concepts, maybe not properties on SKOS XL labels.

**Comment by joelit** [comment]
The [order of ns-prefix registration](https://github.com/NatLibFi/Skosmos/wiki/Configuration#namespace-prefixes) is now a documented feature and the tooltip prefixes were [fixed separatedly](https://github.com/NatLibFi/Skosmos/pull/1356). Closing this issue.

**Comment by miguelvaara** [comment]
In the development server: Added yso and ysoaika prefixes and alphabetized the vocab definitions

**Comment by miguelvaara** [comment]
- The YSO namespace prefix set in config.ttl (in dev and prod).
- The declaration of yso-aika vocabulary moved so it comes after yso in config.ttl (in dev and prod).
- Vocabulary configurations and related settings and also plugin definitions alphabetized in config.ttl files for dev and production servers.
