### ISSUE TITLE
Update Fuseki Docker

### ISSUE THREAD

**Issue by nichtich** [NatLibFi/Skosmos#1415]
The [version of Fuseki used in Docker](https://hub.docker.com/r/stain/jena-fuseki/dockerfile) is 2 years old. There are official Fuseki Docker files at https://jena.apache.org/documentation/fuseki2/fuseki-docker instead.

**Comment by nichtich** [comment]
Well, the official Fuseki docker file does not contain UI so better create your own Dockerfile instead. Meanwhile I [created a Fuseki Debian package instead](https://github.com/gbv/fuseki.deb).

**Comment by osma** [comment]
Thanks for opening the issue.

I agree that we should switch to a more recent version (obviously). Using the official image seems like a good idea to me. I'm not sure if the UI is absolutely required - thoughts?

**Comment by kinow** [comment]
I think the plan in Jena is to further modularize the project so that there is an UI with the admin, without the admin, etc. And at some point maybe there could be a UI added in the Docker Compose recipe -- but probably not for now.

The Apache Jena Dockerfile referenced here has the disadvantage of not being published to Docker Hub, Quay, GH, etc. So I think one possibility would be to somehow update our `docker-compose` to, instead of using `stain/jena-fuseki`, use the Apache Jena `Dockerfile` directly.

Then, later, we can try to add an extra service with the UI + an HTTP Server (tricky part will be handling CORS, and proxying the requests, but doable IMO).

WDYT?

**Comment by kinow** [comment]
Great! I will give it a try and see if I can make it work GUI-less for now.

>It's a pity Apache Jena doesn't publish Docker images.

I will check with Andy to see if it's on the todo list, or if there was a reason for not doing that.

Thanks!

**Comment by kinow** [comment]
Done: https://issues.apache.org/jira/browse/JENA-1949

**Comment by kinow** [comment]
Did a few tests today: https://github.com/kinow/Skosmos/tree/fuseki-docker/dockerfiles/jena-fuseki2-docker

The idea was to get a copy of Jena's Docker image. The first issue I had was that it was not only a `Dockerfile`, but also a few other files used within the `Dockerfile` :disappointed_relieved: 

Then, once I managed to build it, it got a bit complicated to automate everything. stain/jena is able to load a dataset automatically when you create a container with the image.

But from what I undestood, for the Jena image you need to create a folder (`mkdir`), use `tdbloader`, and then execute `docker-compose`. I think it should work if we do the same, but I guess it would be preferable to be able to just run `docker-compose up`?

**Comment by osma** [comment]
Is the `tdbloader` step really necessary? Sounds like it's creating a TDB(2) database so that Fuseki can be used for serving it. But normally Fuseki can also be started without any databases, and new ones can be created at runtime either via the web UI or using the administration protocol API. This is covered in the Skosmos InstallTutorial section [Creating the database from the command line](https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial#b-creating-the-database-from-the-command-line). I think that would be the preferred method because it allows adding new datasets later and of course also updating the data with s-put, s-post etc.

**Comment by kinow** [comment]
Ah, I forgot to test the `curl` calls! Let me test that.

**Comment by kinow** [comment]
All right! It works @osma ! I I modified a little bit the `Dockerfile` to run it without `root` and also use gid & uid `1000`, so the files creates by the container can be edited by the host-user (in most cases, as the UID/GID will be 1000, but that can be changed by the user building it).

I believe this change can be quickly merged back into Jena, so I will send a pull request this week.

@osma, would you like me to try adding the UI to this docker setup too? Or do you prefer to leave that for after Cypress?

**Comment by osma** [comment]
@kinow that's great news!

I think we can live without the Fuseki UI. It can always be added later if it turns out we need it.

**Comment by kinow** [comment]
PR to Jena: https://github.com/apache/jena/pull/1890

**Comment by kinow** [comment]
> PR to Jena: [apache/jena#1890](https://github.com/apache/jena/pull/1890)

Merged, and tested again with Skosmos. Now just need some time to update the docs and one final test.
