### ISSUE TITLE
altLabels disappear when browsed in North Sámi

### ISSUE THREAD

**Issue by nikopartanen** [NatLibFi/Skosmos#1422]
## URL address of the page where you encountered the problem

https://dev.finto.fi/yso/se/page/p5175

## Description of the problem

We see [here](https://dev.finto.fi/yso/fi/page/p5175) that the North Sámi altLabel, vuoiŋŋašhárji,  exists:

![image](https://user-images.githubusercontent.com/6486495/226603793-1a4cab2f-76fa-46be-8011-43a4a9cc9b47.png)

However, it disappears when we select North Sámi as the interface language. The location of the missing element is marked here with an arrow.

![image](https://user-images.githubusercontent.com/6486495/226604292-557f0d94-c205-4e1f-83db-645fd586ac71.png)

The related concept would  be expected to appear at the same place as with other languages.

## The browser you used when the problem appeared

Chrome.

**Comment by osma** [comment]
This only happens when the UI language is set to Northern Sámi.

The reason is that the Northern Sámi translation (UI label) for skos:altLabel is missing:
https://github.com/NatLibFi/Skosmos/blob/a59f251431d27f6458b6c8140593ec409461736c/resource/translations/skosmos_se.po#L543-L545

(this is translated as "Entry terms", "Ohjaustermit" and "Hänvisningstermer" in English, Finnish and Swedish, respectively)

The missing translation should be added in Transifex. Then update the translation files in the Skosmos codebase.
