### ISSUE TITLE
Switch to a new translation platform (instead of Transifex)

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1527]
## Description of the enhancement

We have been using Transifex to manage UI translations maintained by the community. But it has always been a bit difficult to work with and recently the API access has stopped working as well. With Skosmos 3 we have switched to Symfony Translations that [provides direct support](https://symfony.com/doc/current/translation.html#translation-providers) for three translation platforms: Crowdin, Loco (localise.biz) and Lokalise. Obviously we would need to evaluate these and pick one. We could also ask about this on skosmos-users as part of the evaluation.

## Who are the users that would benefit from the enhancement and how?

- Skosmos developers (making it easier to work with contributed translations)
- individuals or organizations that contribute UI translations, e.g. ZBW, ZPID, GBV

## What new functionalities would the enhancement make possible?

It would enable simple pushing and pulling translations from Skosmos to the chosen platform.

## Why is the enhancement important?

Now would be a good time to switch. We can keep using Transifex for Skosmos 2 but switch to something else for Skosmos 3.

**Comment by miguelvaara** [comment]
Are the limits of the free option on Localise sufficient for us?
[https://localise.biz/plans](https://localise.biz/plans)

**Comment by miguelvaara** [comment]
Loco has been contacted and discussions (pricing and technical issues) are ongoing. A more detailed discussion can be found in out team's shared email.

**Comment by miguelvaara** [comment]
## Post-sprint report

In regards to Lokalise, one major question is how much we need to modify and change the Symfony framework, which we already use very minimally. Another important question is whether, as open-source advocates, we have the option to use Lokalise free of charge.

So far, we have explored other translation frameworks, such as Loco and have discussed pricing with them. However, initially we are investigating the possibilities of using Lokalise, especially since Lokalise is also used with VuFind, which is utilized by Finna (https://github.com/NatLibFi/NDL-VuFind2). It is always better if we can find synergies with the Finna team.

**So far, the following has been done:**

A demo account has been set up and,
- the PO translation files for the 21 languages we use have been uploaded to the service (although some languages are still incomplete)
- we have tested the user interface https://app.lokalise.com (in terms of our user community this is important and we will report on this in more detail later).

**The use of the API has been tested, including:**

- Generating the necessary tokens
- Listing all used keys (assets used to fetch translations)
- Retrieving a list of all translation files
- Fetching a link from which the translation files can be downloaded in zip format.

### Method 1 / API:

Lokalise provides a tool for parameterizing API calls:
https://developers.lokalise.com/reference/lokalise-rest-api

**Examples of API usage:**

- List all keys:
get https://api.lokalise.com/api2/projects/{project_id}/keys
```
> curl --request GET \
     --url https://api.lokalise.com/api2/projects/{project_id}/keys \
     --header 'X-Api-Token: {token}' \
     --header 'accept: application/json'
```

- Retrieve a key:
get https://api.lokalise.com/api2/projects/{project_id}/keys/{key_id}
```
> curl --request GET \
     --url https://api.lokalise.com/api2/projects/{project_id}/keys/{key_id} \
     --header 'X-Api-Token: {token}' \
     --header 'accept: application/json'
```

- List all files
get https://api.lokalise.com/api2/projects/{project_id}/files
```
> curl --request GET \
     --url https://api.lokalise.com/api2/projects/{project_id}/files \
     --header 'X-Api-Token: {token}' \
     --header 'accept: application/json'
```

- Download files
post https://api.lokalise.com/api2/projects/{project_id}/files/download
```
> curl --request POST \
     --url https://api.lokalise.com/api2/projects/{project_id}/files/download \
     --header 'X-Api-Token: {token}' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "format": "po",
  "original_filenames": true
}
'
```

Response:
`https://s3.eu-central-1.amazonaws.com/lokalise-live-lok-app-main-assets/files/export/{project_id}}/{automatically generated hash}}/Skosmos-3-locale.zip`

The process could be managed with a script so that the above API call ("Download files") fetches a download link. The downloaded zip package is then unzipped into the directory where the system's language files are located. The desired file format can be specified.

Regarding the file format, we would like to change from PO files to JSON format files so that they can be more easily used directly on the frontend if needed.

### Method 2 / Symfony Console:

In testing Symfony usage, we were unable to properly download translations when attempting to do so with Skosmos. In the initial testing phase, tests were conducted in a separate Symfony project without Skosmos.

The process followed was:

```
> mkdir symfony-tests && cd symfony-tests

> wget https://get.symfony.com/cli/installer -O - | bash

> export PATH="$HOME/.symfony5/bin:$PATH"

> symfony new bare-symfony --version="6.4.*"

> cd bare-symfony/

> vim .env
```

(.env) Add the line:
_LOKALISE_DSN=lokalise://{project-id}:{token-for-reading}@default_

`> vim config/packages/translation.yaml`

Add the following:

```
framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
            lokalise:
                dsn: '%env(LOKALISE_DSN)%'
				# List all the languages you want to download
                locales: ['en', 'fr', 'it'] # test langs

```
```
> symfony console translation:pull lokalise --format json

> cd translations

> ls 
```
Listing of the _ls_:
_skosmos_en.en.json
skosmos_fr.fr.json
skosmos_it.it.json_

Looks like we need to take a closer look at how we are naming those files.

`> less skosmos_it.it.json`

```
{
    "%search_count% results for '%term%'": "%search_count% risultati per '%term%'",
    "404 Error: The page %requested_page% cannot be found.": "Errore 404: La pagina %requested_page% non pu\u00f2 essere trovata.",
    "A-Z": "A-Z",
    "About": "Informazioni",
    "About page": "Informazioni",
    "All %d results displayed": "Tutti i %d risultati mostrati",
    "Alpha-nav": "Ordine Alfabetico",
    "Alphabetical index": "Indice alfabetico",
    "Alternate terms": "Termini alternativi",
...
```


Here is what needs to be looked into:

In the class src/model/Model.php, some small changes need to be made to ensure that the system reads json files properly instead of po files.

```
public function __construct($config)
{
    $this->globalConfig = $config;
    $this->initializeLogging();
    $this->resolver = new Resolver($this);

    foreach ($this->getConfig()->getLanguages() as $langcode => $locale) {
        if (is_null($this->translator)) {
            $this->translator = new Translator($langcode);
        }
        $this->translator->addLoader('po', new PoFileLoader());
        $this->translator->addResource('po', __DIR__.'/../../resource/translations/skosmos_' . $langcode . '.po', $langcode);
    }
}
```

Possible challenges:

It is still unclear how Symfony and its required components are added to Skosmos in a way that keeps the installation minimal. We aim to keep Symfony's part in the application small while ensuring that it does not unnecessarily interfere with the current functionality of the application.


### Method 3 / Lokalise API v2

Lokalise also provides its own PHP implementation:

https://github.com/lokalise/php-lokalise-api

This option needs to be tested further. If Lokalise integration is chosen, we need to consider the options between direct API usage, Symfony console usage, and Lokalise's own PHP implementation.
