### ISSUE TITLE
Turtle output with fragment URIs is invalid

### ISSUE THREAD

**Issue by namedgraph** [NatLibFi/Skosmos#1591]
## Description of the problem
I copy-pasted Skosmos Turtle output into http://ttl.summerofcode.be and it does parse, nor does it with Jena's riot

The error:
```
Expected punctuation to follow "https://data.beamery.com/aaa/bbb/ccc/1287" on line 14.
```
The relevant bit of data looks like this:
```
@prefix smth: <https://data.beamery.com/aaa/bbb/ccc/> .

... skos:relatedMatch smth:1287#this

```

I don't think the `prefix:local-name#fragment` syntax is valid. You should look into the RDF I/O library that is producing this.

**Comment by namedgraph** [comment]
@osma can you confirm?

**Comment by osma** [comment]
Thanks for the report @namedgraph . Indeed the likely culprit here is the EasyRdf library that Skosmos uses for RDF handling; specifically we use the [sweetrdf/EasyRdf](https://github.com/sweetrdf/easyrdf) fork. Currently we have pinned the dependency on version `1.7.*`:

https://github.com/NatLibFi/Skosmos/blob/main/composer.json#L8

The same version is currently used both on the `main` branch (Skosmos 3, heavily WIP) and on the legacy `skosmos-2` branch that you are likely using.

It seems like this kind of bug was fixed in [sweetrdf/EasyRdf 1.10](https://github.com/sweetrdf/easyrdf/releases/tag/1.10.0): see https://github.com/sweetrdf/easyrdf/pull/35 for the actual PR. Though I'm not sure if this is exactly the same bug or just similar. The most recent release is [1.11](https://github.com/sweetrdf/easyrdf/releases/tag/1.11.0).

@namedgraph can you provide a minimal test case that demonstrates the problem? Your report now just included the symptoms but not the original vocabulary data that was used. A test case would allow testing newer EasyRdf versions to see if the problem goes away.

One possible complication when upgrading EasyRdf (if that's what is needed) is that Skosmos 2 still supports PHP versions 7.3 and 7.4, but sweetrdf/EasyRdf dropped support for 7.x in version [1.9](https://github.com/sweetrdf/easyrdf/releases/tag/1.9.0).

**Comment by osma** [comment]
@nikopartanen Can you add the SKOS-XL examples from YSO that we know of?

**Comment by nikopartanen** [comment]
Certainly! This one breaks because of the North Sámi label:

http://www.yso.fi/onto/yso/p3448

This breaks due to the label that marks outdated usage:

http://www.yso.fi/onto/yso/p17004

These are two major categories for which we currently use SKOS-XL. I think this problems involves all SKOS-XL labels that we have. I can collect a larger list of these if needed? The North Sámi labels are generated automatically and the cultural sensitivity labels are done manually.

**Comment by osma** [comment]
This seems to be a bug in sweetrdf/easyrdf 1.7.x which we are currently using in Skosmos 2. I tested upgrading to a more recent easyrdf release (the newest one is 1.14.1) and the problem went away with version 1.10.x and above. I believe the fix was made in this PR: https://github.com/sweetrdf/easyrdf/pull/35

So the simple solution is to upgrade easyrdf to a more recent version. The only concern I have is that easyrdf 1.10.x (and above) requires PHP 8.0+, which means we will have to drop support for PHP versions 7.3 and 7.4. No big deal, because 7.x has been EOL for some time now.

**Comment by osma** [comment]
The fix has now been merged to the `skosmos-2` branch and will be part of the next 2.x release, which will hopefully be released next week.

The same fix needs to be done also for Skosmos 3, so I'm leaving the issue open.
