### ISSUE TITLE
List top concepts?

### ISSUE THREAD

**Issue by danmichaelo** [NatLibFi/Skosmos#193]
When visiting a thesaurus you might want to search for some specific concept, and search as a starting point works really well in Skosmos (the tree and breadcrumb navigation also works really well once you've in). But you might also be interested in how the thesaurus is structured, and a good starting point for browsing can be the top concepts.

To me it seems like it could be a good idea to have a list of top concepts on the vocabulary home view. Is this something you have discussed? I'm also curious why there is a `FILTER (?property != skos:hasTopConcept)` in `GenericSparql:queryConceptScheme()`? Normally there shouldn't be so many top concepts that there should by any performance benefit from this?

I also find it slightly confusing that the "Hierarchy" tab isn't visible until you open some concept. Perhaps it would work well to show the top concepts there at the start?

**Comment by henriyli** [comment]
The hierarchy tab is disabled by default on the vocabulary home page, but it can configured in the vocabularies.ttl. The feature can be enabled by setting ``` skosmos:showTopConcepts "true";```  for the vocabulary in question. The reason we have chosen to disable it by default is because in less hierarchical datasets (such as classifications) it can be uninformative as there might be very many top concepts. We treat all classes without superclasses as topConcepts because otherwise they wouldn't show in the hierarchy at all.

**Comment by danmichaelo** [comment]
Thanks, that's brilliant!
