### ISSUE TITLE
Get rid of relative URL in base href (breaks IE9)

### ISSUE THREAD

**Issue by catecara** [NatLibFi/Skosmos#225]
IE9, Skosmos v1 for AGROVOC. It does not get the css, and when searching for a term, it return page not found (it looks for an incomplete path, first part is missing).
 
Quick fix was to use this in line 4 of view/light.twig:
<base href="http://aims.fao.org{{ CurrentUrl }}">

Note that we use a redirect to turn the "real" url given by our skosmos installation into the "standard" aims.fao.org url. IE does not handle this well.

**Comment by osma** [comment]
I'm not sure why we even have a base href tag in the HTML code. All links should be relative. But there might be some edge case that requires it.

The W3C spec apparently says that the base href value should be an absolute URL. We have a relative URL in there and IE9 doesn't seem to like it.

Anyway I think the right solution is to get rid of the base href tag completely, at least by default.

For FAO I think you still need the base href tag in the HTML, because you're publishing the Skosmos front page at another URL (http://aims.fao.org/standards/agrovoc/functionalities/search) than where it "naturally" sits (http://aims.fao.org/skosmos/agrovoc/en/). So if we get rid of the base href tag by default in Skosmos, we will either need to introduce a configuration directive to explicitly include one (with a specific absolute URL set in the configuration), or you will just have to hack the Twig template as you already did to fix this.

**Comment by henriyli** [comment]
The problem here is that without the base href set the relative links break when content is loaded by ajax. For example when moving from the alphabetical index to a concept page the path fix is then longer correct in the sidebar links that were generated for the alphabetical index page.

**Comment by osma** [comment]
Suggested solution:

1. All HTML pages have a base href that points to the Skosmos front page. All links on the page are relative to that, regardless of whether they've been loaded by ajax etc.
2. The base href value can be set by a configuration option in config.inc (BASE_URL). If not set, the default should be guessed from the server environment, e.g. based on [this recipe](http://blog.lavoie.sl/2013/02/php-document-root-path-and-url-detection.html). This detection should work at least in the simple case where there is no proxy in front of apache.

**Comment by osma** [comment]
Looks good now, though path_fix is still used at least in javascript code

**Comment by osma** [comment]
There are still absolute links for language choices at http://dev.finto.fi/yso/fi/
(both for choosing UI language, and for choosing content language)

The protocol is forced to http:// in https://github.com/NatLibFi/Skosmos/blob/master/view/topbar.twig#L6
