### ISSUE TITLE
Concept types shown as URIs, not labels, on first search

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#295]
## At which URL did you encounter the problem?
http://dev.finto.fi/fi/

## What steps will reproduce the problem?
1. Start a new browser session (clear the local storage and/or use incognito/private window)
2. Go to front page
3. Enter a search term e.g. "kissa"
4. Wait for the dropdown

## What is the expected output? What do you see instead?

Expected to see the types of concepts as labels. Instead seeing URIs. In subsequent queries the types are shown as labels.

Maybe the types method is too slow? Or the order of operations is wrong.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox and Chromium

**Comment by henriyli** [comment]
If the type labels can't be found cached in local storage a query is made to the REST API when the page is first opened. The problem is that in the Finto-case the types query takes 9ish seconds to complete. If the autocomplete shows results before the response has been parsed (and cached) the URIs are shown.
