### ISSUE TITLE
Is it possible to search inside the labels (using tokenization) ?

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#395]
Hello

SKOSMOS currently searches for concept labels at the beginning of the label only, even if the label contains multiple words. e.g. a search for "fra" does not match concept "academic fraud". The workaround is to search for "*fra*" instead.

Is there a configuration in the JenaText index that would permit a search on "fra" to match "academic fraud" ? does it require a new version of Fuseki ?

Thanks

**Comment by osma** [comment]
Yes, currently Skosmos treats the full label as a single token. It will not match individual words in the label. You can search for "*fra*" to match "academic fraud".

But in upcoming Skosmos 1.4 the responsibility for all text searches is finally being given to jena-text, which can be configured with different analyzer. I think if you [configure jena-text](https://jena.apache.org/documentation/query/text-query.html#configuring-an-analyzer) to use e.g. SimpleAnalyzer, that should enable it to match words within labels. 

SimpleAnalyzer has been available for some time so it is in Fuseki 1.3.0/2.3.0 which will be required by Skosmos 1.4 anyway. Fuseki 1.3.1/2.3.1 brought [configurable analyzers](https://jena.apache.org/documentation/query/text-query.html#configurableanalyzer) which are even more flexible. But unfortunately Fuseki 1.3.1/2.3.1 has a bug (JENA-1093) which makes it less suitable for use with Skosmos. It was fixed today in jena master so the most recent code should work again.

Please try using SimpleAnalyzer with Skosmos 1.4 (current master) and report back on your experiences, for example on skosmos-users.

I'm closing this issue because it's not really something that has to be done for Skosmos.
