### ISSUE TITLE
Make use of different text indexes optional

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#422]
Fuseki text currently does not allow for a property (say, skos:prefLabel), to go into multiple text indexes (say. "pref" for Skosmos, and a general index for all text properties).

It would be great the Skosmos functionality would not require particular index definitions.

**Comment by osma** [comment]
> Fuseki text currently does not allow for a property (say, skos:prefLabel), to go into multiple text indexes (say. "pref" for Skosmos, and a general index for all text properties).

Right. This is a limitation of jena-text. You could open an issue in the Jena JIRA if you'd like to change this. It should be doable with relatively little effort - the only question is, if several indexes are defined for a specific property (e.g. skos:prefLabel) and a query comes in targeting skos:prefLabel, then which index should be queried? But I think at least the common case of having one general index (which could be set as the default index) plus property-specific indexes would be possible to support. (Disclaimer: I'm also one of the maintainers of jena-text)

> It would be great the Skosmos functionality would not require particular index definitions.

There are some requirements that must be fulfilled for Skosmos to work properly, for example skos:prefLabel, skos:altLabel and skos:hiddenLabel must be indexed and the analyzer for these must be case-insensitive. These should be documented in the Skosmos wiki.

Also the current query for the alphabetical index doesn't double-check the results from the text index against the stored triples, so if you mix in other properties in the same index with skos:prefLabel and/or skos:altLabel, the results may be surprising. The check should probably be added (the text search query already does that), but it might affect performance slightly so that should be measured too.

**Comment by osma** [comment]
Checking for the existence of triples seems to work without any significant performance impact, but I think I'll wait for some more measurements before backporting this to 1.4.

**Comment by osma** [comment]
Doesn't seem to affect performance, so I've added this to the v1.4-maintenance branch.

**Comment by osma** [comment]
Documented the Skosmos requirements for jena-text configuration:
https://github.com/NatLibFi/Skosmos/wiki/InstallFusekiJenaText#alternative-configurations

All done, closing.
