### ISSUE TITLE
Global search is slow yet again

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#448]
## At which URL did you encounter the problem?
http://dev.finto.fi/fi/search?q=demokrat*
http://dev.finto.fi/fi/search?q=n%C3%A4ytelm%C3%A4t

compare with:
http://finto.fi/fi/search?q=demokrat*
http://finto.fi/fi/search?q=n%C3%A4ytelm%C3%A4t

## What steps will reproduce the problem?
1. Perform global search (all languages) for "demokrat*" or "näytelmät"

## What is the expected output? What do you see instead?

The search takes around twice as long with dev.finto.fi (current master) as with finto.fi (1.4-maintenance). Should investigate what causes the difference.

**Comment by henriyli** [comment]
My guess would be that since the current version of the code actually follows the default search limit of 100 concepts it takes a bit longer to complete since it has to make the concept info query for more concepts. The difference in "demokrat* " is 80 vs 20. The paging seems to be broken in the old version too so you can't even see the whole list even if you wanted to.

**Comment by osma** [comment]
Good enough for 1.5.
