### ISSUE TITLE
Support classifying vocabularies by type in vocabularies.ttl

### ISSUE THREAD

**Issue by amiika** [NatLibFi/Skosmos#458]
Vocabularies API should have type support for categorizing or filtering vocabularies.

This could be implemented as new classification in skos and used:
```
<ex:myScheme> a skos:ConceptScheme .
<ex:myScheme> dc:type ext:Glossary .
```

 or multityping by creating new linked data vocabulary:
`<ex:myScheme> a skos:ConceptScheme ; 
                            a ext:Glossary . `

Vocabulary api could also support typing without any vocabulary classification by returning all rdf:type that are associated with the scheme. 

Vocabulary categorization in other hand is bit difficult, but creating list would be better than allowing arbitrary types. Used terms are also controversial so the classification should have definitions for the types. Somewhat limited list can be found at: http://publications.europa.eu/mdr/authority/dataset-type/index.html

My suggestions for vocabulary classes:

Taxonomy (Taksonomia)
Thesaurus (Asiasanasto)
Subject headings (Jäsennetty asiasanasto?)
Ontology (Ontologia)
Metadata vocabulary (Metatietosanasto)
Classification scheme (Luokitus)
Terminological Dictionary (Terminologinen sanasto)
Glossary (Määrittelevä sanasto)

**Comment by osma** [comment]
There is already support for a categorization of vocabularies using an embedded skos:ConceptScheme in vocabularies.ttl and dc:subject properties for vocabularies. This is used in Finto for classification of vocabularies by domain (general, society, geo etc.) which is loosely based on the top level of the UDC classification.

Would it help you if this was exposed in the `vocabularies` API as a search criterion?

I understand that your classification is more technical in nature, i.e. what *kind* of vocabulary something is rather than what the content is *about*.

**Comment by osma** [comment]
I think there are actually several related issues here:

1. add support for classifying vocabularies by type in vocabularies.ttl (e.g. the suggested classes above)
2. extend the REST API so that it is possible to search for vocabularies by type (or subject?)
3. probably the vocabulary type information should be shown in the UI as well

1 is a prerequisite for 2 and 3, obviously.

This issue should be split. Let's keep this issue as addressing only 1, and create new issues for 2 and (possibly) 3.

**Comment by amiika** [comment]
Great! We need 2 (and 1) but 3 would also be nice. 

Currently types are "encoded" in the vocabulary names in the UI, but some subtle subtitles in the vocabulary list would make it easier to find for example: all classifications schemes used in science and medicine.

**Comment by amiika** [comment]
Is there a support for filtering vocabularies with type in /vocabularies API or not?

**Comment by osma** [comment]
@amiika Currently not. This issue was only about making the information available, so you can see the vocabulary types in the /vocabularies response, but there is no server-side filtering. If you need that, please open a new issue.

**Comment by amiika** [comment]
Any idea of the type-classification that should be used? We can of course start using "whatever" uri:s but i dont think that is a good idea in the long run.

http://publications.europa.eu/mdr/authority/dataset-type/index.html is a good start but it is lacking Terminological dictionary, Glossary etc.

**Comment by osma** [comment]
Sorry, I don't have any better idea. The implementation is generic though, any SKOS classification (that you probably need to include within vocabularies.ttl currently) will do.
