### ISSUE TITLE
Add @base to JSON-LD contexts

### ISSUE THREAD

**Issue by amiika** [NatLibFi/Skosmos#536]
Vocabulary specific API returns empty uris. For example 'http://api.dev.finto.fi/rest/v1/yso/' returns:

```
..
"uri": "",
  "id": "yso",
  "title": "YSO - Yleinen suomalainen ontologia",
  "defaultLanguage": "fi",
..
```

I would be nice to have proper service specific uris for vocabularies for example "uri : "http://finto.fi/yso/".

**Comment by osma** [comment]
The reason it's empty is that in JSON-LD, an empty subject URI will be interpreted as the URL of the document, so in this case the URL is implicitly "http://api.dev.finto.fi/rest/v1/yso/" .

It's a bit unclear what the URL/URI returned for a vocabulary by the REST API should actually be, as there are many alternatives:
1. The URL that was called and returned this JSON-LD document, i.e. "http://api.dev.finto.fi/rest/v1/yso/" or just ""
2. The URL of the web page of the vocabulary, e.g. "http://finto.fi/yso/"
3. The URI namespace of the vocabulary, "http://www.yso.fi/onto/yso/"

Currently we have chosen 1, since this data is not about the web page of the vocabulary (2) nor is it directly data stored within the vocabulary (3), as it's mostly about how the vocabulary is configured/represented in Skosmos.

Can you elaborate on why you would need this? Would it help to have something like `"homepage": "http://finto.fi/yso/"` instead? (where `homepage` could be defined as `foaf:homepage` in the JSON-LD context)

**Comment by amiika** [comment]
Empty uri is interpreted as base uri, but since there is no @base in the context the uri is not known.

I would like to use the API:s as source for Linked Data that can be directly merged into a graph. Currently those "implicit" URI:s would merged to one resource which is obviously wrong. IMHO interpreting and making up identifiers should not be left to the API users.

Suggestions:

1) Add @base to JSON-LD contexts if ""/empty uris are used. For example: "@base": "http://api.dev.finto.fi/rest/v1/yso/"

(References to actual representation of vocabularies like "homepage": "http://finto.fi/yso/" would be nice but it is different issue)

**Comment by osma** [comment]
Okay, the `@base` declaration makes sense and shouldn't be difficult to add.
