### ISSUE TITLE
Version API

### ISSUE THREAD

**Issue by amiika** [NatLibFi/Skosmos#538]
This is new feature request for automatically added modification date or unique version identifier.

This would be useful for polling and updating the whole vocabulary only if some changes have been made. Modification date or maybe urn:uuid identifier for the current version should be generated by Finto when new version of vocabulary is uploaded.

This could be implemented as new /version API that return only the version information or maybe added as new metadata to vocabulary specific api.

**Comment by osma** [comment]
We have something like this, at least in Finto.

All Finto vocabularies should have a dct:modified timestamp on the ConceptScheme. It's not directly exposed, but if you ask for the data about the ConceptScheme URI, you will get the timestamp as well. This is added by Skosify, but of course, not all vocabularies that Skosmos may be used with have such timestamps.

Some Finto vocabularies also have dct:modified (and often dct:created) timestamps on individual Concept instances. Vocabularies with concept timestamps include YSA, Allärs, YSO, MUSA and CN. The granularity varies a bit: in YSO the timestamps are inferred from the data and they have day level granularity, while the other timestamps originate from MARC records and have much finer granularity.

Also the full RDF downloads of the vocabularies are in practice just regular files served by Apache, so you can make a HTTP HEAD request to query for their timestamp only, or use mechanisms such as If-Modified-Since.

Can you comment on whether these are enough for your use case? If not, do you have a more specific request?

The problem from the Skosmos point of view is that it only "sees" graphs from the SPARQL endpoint (Fuseki typically), but the endpoint doesn't really manage any timestamp data. Skosmos cannot make a SPARQL query such as "when did the data in graph X last change", at least not with Fuseki. So implementing a generic mechanism is hard. We actually have graph-level timestamps in the Finto Fuseki database, stored in a separate RDF graph, but Skosmos isn't currently aware of those, they are only used for syncing the Fuseki graphs with files from the Finto-data GitHub repository.

**Comment by osma** [comment]
> dct:modified could be enough, but it should be generated and overwritten by skosmos etc. I would prefer some skosmos specific namespace onki:modified etc. to be sure that timestamps are not conflicting with user modified content. These timestamps should be accessible from /vocaublaries or /{vocid}/vocabularyStatistics etc. API.

The problem with this is that Skosmos is read-only and is not responsible for maintaining the data in the triple store. Skosmos cannot know when the data in the triple store has last changed. It also has no place where to write such a timestamp, even if it knew.

> Now how would i do HTTP HEAD request based on /vocabularies API?

You need to do this in two steps, because the /data method serves a 302 redirect to the actual URL where the data can be found.

1. `curl -I http://api.finto.fi/rest/v1/yso/data`

This will give you, among other headers, `Location: http://api.finto.fi/download/yso/yso-skos.ttl`

Note the URL and use it in the follow-up request:

2. `curl -I http://api.finto.fi/download/yso/yso-skos.ttl`

This will give you a Last-Modified header.

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
