### ISSUE TITLE
Hierarchy visible after clicking a concept in the A-Z tab

### ISSUE THREAD

**Issue by nicky508** [NatLibFi/Skosmos#548]
## At which URL did you encounter the problem?
Every time entering the Skosmos application.

## What steps will reproduce the problem?
1. Go to the Skosmos application.
2. Go to Hierarchy tab (the hierarchy tab is completely empty).
3. Go to A-Z tab.
4. Click a concept.
5. Go to Hierarchy Tab (Now the topConcepts are visible in the tab).

## What is the expected output? What do you see instead?
I would expect to see the topConcepts at the moment I enter the Skosmos application. I should not have to click a concept in he A-Z tab first, before the topConcepts are visible in the Hierarchy tab.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox. 

##Checked with Finto version
Checked it with the Skosmos version which is running by dev.finto.fi, here the problem does not occur and the hierarchy tab is filled immediately without clicking a concept in the A-Z tab.

**Comment by osma** [comment]
Thanks for the report. Can you please provide a URL where this happens?

The display of top concepts is controlled by a vocabulary-specific setting `skosmos:showTopConcepts`, which defaults to false, because many SKOS vocabularies don't have top concepts. So whether you will see the tab or not depends on this setting. (see [documentation](https://github.com/NatLibFi/Skosmos/wiki/Vocabularies#vocabulary-configuration-vocabulariesttl))

**Comment by osma** [comment]
If you have a local installation that is not accessible, please try setting `skosmos:showTopConcepts true` in your vocabularies.ttl and see if that helps.

**Comment by nicky508** [comment]
A sorry. It is not a local installation anymore, so I can share. This is the link: [http://nfpa.firebrary.com/nfirs/en/index ](url). If you go directly to the hierarchy tab, you do not see anything. Then go to the A-Z tab and click on one random label. Then go back to the hierarchy tab and suddenly all top concepts are visible.

The setting "skosmos:showTopConcepts" is set to true

**Comment by henriyli** [comment]
Skosmos seems to be unable to find the top concepts for nfirs. http://nfpa.firebrary.com/rest/v1/nfirs/topConcepts?lang=en

I think this might be a configuration issue since they can be seen in the concept hierarchy like you described. The vocabularies.ttl at the link you gave states the mainConceptScheme as https://firebrary.nfpa.org/data/terms/data_dictionary however in the data it would appear to be http://firebrary.nfpa.org/data/terms/data_dictionary. See: http://nfpa.firebrary.com/rest/v1/nfirs/data?uri=http%3A%2F%2Fnfpa.firebrary.com%2Fdata%2Fterms%2Farson_module&format=text/turtle

You could try changing that to http and see if it helps. (void:urispace also has https instead of http but I'm not sure if that makes a difference here)

**Comment by nicky508** [comment]
Ah oke, I will look into it. I let you know.

**Comment by nicky508** [comment]
It works, we made a mistake by using .org in the vocabularies instead of .com.

Thanks for all help.
