### ISSUE TITLE
Support alternative Turtle parsers for vocabularies.ttl parsing

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#573]
Parsing vocabularies.ttl may take several seconds of CPU time. This happens because the EasyRdf native Turtle parser [is very slow](https://groups.google.com/d/msg/easyrdf/fkdZ7snm-jU/8epkU-lIDQAJ). This does not matter with a small vocabularies.ttl which has only one or two vocabularies, but becomes significant with ~30 vocabularies in Finto.

Normally the vocabularies.ttl is cached by APC, but when this fails for some reason (as recently happened in Finto), the performance hit can be huge.

EasyRdf also supports two alternative Turtle parsers: rapper and Redland. We should support at least one of these faster alternatives.

**Comment by henriyli** [comment]
I tried implementing support for Rapper. Using Rapper was very fast. However, we still need to read the prefixes from the vocabulary configuration. So we would still need to parse the prefixes with the slow turtle parser. We chose to improve the EasyRdf_Parser_Turtle perfomance instead (see e01a7c8). With my vocabulary configuration the parsing now takes 300ms instead of 3000ms. It's still around 10 times slower than with rapper, but atleast we're still getting the prefixes without using two parsers.

**Comment by henriyli** [comment]
I fixed an issue with unreading the first character of a line in b31cdb9. It should now be possible to use the new parser implementation for parsing the prefixes. There's still something wrong with blank node parsing though.

**Comment by osma** [comment]
No longer urgent, moving to Blue Sky

**Comment by osma** [comment]
Parsing is nowadays much faster also with vanilla EasyRdf, as the improvements done here were contributed upstream.

Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
