### ISSUE TITLE
using URNs for identifying concepts

### ISSUE THREAD

**Issue by kopacsi** [NatLibFi/Skosmos#609]
We can identify the concepts in a vocabulary by their URI building up from an http URI prefix (e.g. <http://www.statistik.at/oefos2012/>) and the numeric id provided in the vocabulary file, which is currently supported by Skosmos.
Generally it is all right, since by the URLs users can easily look up the concept in the resource where the URL points to. But there are certain cases - for example the vocabulary of OEFOS (http://vocab.phaidra.org/skosmos/oefos12/en/) -, when there is no other resources, no linked database  where the URL can point to. (The above given URL - http://www.statistik.at/oefos2012/ -  for prefix does not exist, but works as an URI). In this case using URN for URI instead of URL would be a good solution. With this URN we could uniquely identify the object of the vocabulary without providing an existing or non-existing URL. In the triple store we can upload such prefixes (e.g. @prefix oefos: <urn:x-vocab:at:oefos:2015:>, but Skosmos does not support it, it simply can not load and display those vocabularies, where the concepts are identified with URNs instead of http URIs.

## At which URL did you encounter the problem?
http://vocab.phaidra.org/skosmos/oefos12/en/

## What steps will reproduce the problem?
1. provide @prefix oefos: <urn:x-vocab:at:oefos:2015:> in the vocabulary file
2. upload it to the fuseki server
3. try to view it in Skosmos

## What is the expected output? What do you see instead?
Expected: to see the concatenated urn:x-vocab:at:oefos:2015: and the numeric id of the concept
Instead: the concept can not be displayed 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Chrome

**Comment by osma** [comment]
Not sure why this doesn't work as-is. URNs are URIs after all. But maybe somewhere in Skosmos code there are checks for `http[s]://` patterns which obviously won't work with plain URNs.

When you say there's "no other resources, no linked database where the URL can point to", have you considered that Skosmos itself could be that database? That's what we do - we have the URI namespaces "wired up" so that they redirect to Skosmos, which can then serve either HTML or RDF versions of concepts. See [ServingLinkedData](https://github.com/NatLibFi/Skosmos/wiki/ServingLinkedData) in the wiki for details.

PS. Sorry for the very late response!

**Comment by gonter** [comment]
Sorry for the late response from our side.  I have to take over for Sandor Kopacsi who originally opened this issue.

The problem at hand is to have valid (resolvable) and stable URIs, e.g. for concepts like "502049 Economic history" which is loaded as [1] or [2].  Sandor "invented" URLs like [3] which do not resolve and would lead to a conflict with the owners of the domain statistik.at sooner or later.  That's why we considerd URNs like [4].

So, your prosposal would be to generate URLs like [5] and rewrite it to a link like [6] (or [6b] for now).  That would indeed be a nice way.

Thanks for pointing this out.

* [1] http://vocab.phaidra.org/skosmos/oefos12/en/page/502049
* [2] http://vocab.phaidra.org/skosmos/oefos12/de/page/502049
* [3] http://www.statistik.at/oefos2012/502049
* [4] urn:(x-)vocab:at:oefos:2012:502049
* [5] http://vocab.phaidra.org/oefos2012/502049
* [6] http://vocab.phaidra.org/skosmos/entity?uri=http://vocab.phaidra.org/oefos2012/502049
* [6b] http://vocab.phaidra.org/skosmos/entity?uri=http://www.statistik.at/oefos2012/502049

regards, Gerhard Gonter

**Comment by osma** [comment]
@gonter Exactly. You're of course free to decide whether to use `vocab.phaidra.org` both as the identifier space and the Skosmos URL space. You could also use something like `id.phaidra.org` for the identifiers. We generally try to keep the identifier URI spaces quite separate from where Skosmos is installed.

**Comment by gonter** [comment]
Thanks for that hint too.  Why would you separate vocab and id as different hostnames?

GG

**Comment by osma** [comment]
It's easier to ensure persistent URIs when you use a separate URI/URL space for identifiers that is independent of the technical infrastructure. [Cool URIs don't change!](https://www.w3.org/Provider/Style/URI)

Is there still something that needs to be fixed on the Skosmos side or can this issue be closed?

**Comment by gonter** [comment]
Ok, right!  I think this makes sense and that solution is viable.

regards, Gerhard Gonter
