### ISSUE TITLE
Special marker for broken links 

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#613]
Some concepts have links (exact match, close match etc) which are not working. While this link data may be useful for someone, it would be user-friendly to mark these broken links with a color code or, perhaps better still, an information icon and a notification.

Example:
http://finto.fi/tero/fi/page/TTL44

**Comment by osma** [comment]
It would probably make sense to differentiate between three possible situations:
1. The URI resolves properly and returns RDF data (e.g. a concept label) that we can display
2. The URI resolves, but the data could not be parsed (e.g. it is a plain HTML web page)
3. The URI did not resolve (e.g. HTTP error, unresolvable hostname or timeout)

It is especially case 3 that should be marked

**Comment by kouralex** [comment]
I was just wondering how this should be resolved since this requires a request to possibly multiple external hosts and on every page load in case we want to have the most updated information (or maybe we can accept cached responses?). The 2nd situation @osma profoundly mentioned affects vocabularies currently offered on finto.fi, I wonder if - at least for intra-endpoint linkings - we could provide an efficient solution.

**Comment by osma** [comment]
We already cache succesful responses for Linked Data requests.  I think relying on the cache is OK. The marker should be shown when a request was made and it failed. Right now we perform the request (unless a cached response exists) but do not indicate whether it was succesful or not.

In other words, this issue is not about performing more requests than we already do, but showing to the user whether they were succesful or not.

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
