### ISSUE TITLE
Enable downloading a vocabulary in MARC

### ISSUE THREAD

**Issue by kouralex** [NatLibFi/Skosmos#734]
As @osma pointed out in https://github.com/NatLibFi/Skosmos/issues/733#issuecomment-371744149, the REST API and related Skosmos code should be aware of `.mrc` and `.mrcx` file types configured via `void:dataDump`s in `vocabulary.ttl` to be able to serve vocabularies in those downloading formats.

**Comment by osma** [comment]
So the idea would be that in `config.ttl` there can be a setting like this:

```
        void:dataDump <http://dev.finto.fi/download/yso/yso.mrcx> ;
```

Changes needed in the Skosmos codebase to support this:

1. [VocabularyConfig.getDataURLs()](https://github.com/NatLibFi/Skosmos/blob/master/model/VocabularyConfig.php#L111) should be changed so that it recognizes the `.mrcx` extension and returns the correct MIME type (`application/marcxml+xml`).
2. HTML template code for the download link should be added to the `download-links` section in the template [vocab-shared.twig](https://github.com/NatLibFi/Skosmos/blob/master/view/vocab-shared.twig#L47).

**Comment by jarmosaarikko** [comment]
How  would you produce the two languages in separate files, i.e. yso-fi.mrcx AND yso-sv.mrcx? Would it be as simple as adding two separate void dataDump <filename> rows?

**Comment by osma** [comment]
@jarmosaarikko Good point. I think Skosmos needs to know the language of each of those `mrcx` files - and parsing it from the file name is not good. It already understands a `dct:format` property on the dump URL; we could add support for `dct:language` as well. So the configuration file would look like this:

```
:yso
[...]
    void:dataDump <http://dev.finto.fi/download/yso/yso-fi.mrcx>, <http://dev.finto.fi/download/yso/yso-sv.mrcx> .

<http://dev.finto.fi/download/yso/yso-fi.mrcx>
    dct:format "application/marcxml+xml";
    dct:language "fi" .

<http://dev.finto.fi/download/yso/yso-sv.mrcx>
    dct:format "application/marcxml+xml";
    dct:language "sv" .
```

Then the `getDataURLs` method would need to return also the language of each of those URLs (or perhaps better, take a `lang` parameter that filters the returned URLs) so that we can show the link to the right language version. Or do we want to show the links to all language versions in any case, regardless of the current UI/content language?

**Comment by kouralex** [comment]
I am closing this since this was fixed in https://github.com/NatLibFi/Skosmos/pull/877.
