### ISSUE TITLE
Some concepts are not alphabetically ordered ( !* )

### ISSUE THREAD

**Issue by aturbati** [NatLibFi/Skosmos#752]
## At which URL did you encounter the problem?
http://artemide.art.uniroma2.it:8081/agrovoc/agrovoc/en/
## What steps will reproduce the problem?
1. load agrovoc in skosmos
2. open Alphabetical tab
3. there is the !* subtab containg some concepts not being indexed alphabetically

## What is the expected output? What do you see instead?
I do not understand why there are some concepts not being indexed by skosmos (I'm not sure if the problem is with Skosmos or with Fuseki), so, they are not returned by a search. I've looked at the RDF data definition of these concepts, and they have the same similar triples of the other indexed concepts.  

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Chrome, Firefox

**Comment by osma** [comment]
These labels start with a space character. From the Turtle serialization:

```
" American plum line pattern virus"@en
" chrysanthemum leafminer"@en
```

It's not good that they end up on the `!*` tab, but the underlying problem is with the data.

Skosify fixes extra whitespace if you preprocess your data with it (though it's rather slow to run it on AGROVOC and needs a lot of memory).
