### ISSUE TITLE
Concept type not mentioned in enter search results

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#776]
Concept type is not mentioned in enter search results. In ontologies where there are several concept types this information would be useful. In domain ontologies which are linked to general ontologies (such as JUHO, which is linked to YSO) this information is crucial. At the moment, enter search does not show whether a given concept is a domain ontology concept or a general ontology concept. This information may be inferred from the concept's URI, but not in all cases. And as far as I know, URI name space isn't exactly meant for indicating concept types.

See also: https://github.com/NatLibFi/Skosmos/issues/546

**Comment by kinow** [comment]
Maybe for this and for #546 we could have a separate section like "Advanced Search", and leave the current feature untouched for now.

Advanced search could have specific filters, by Concept Type, Concept, or maybe even custom SPARQL predicate. WDYT @tpalonen ?

**Comment by tpalonen** [comment]
@kinow the feature you suggest already exists. Search results can be narrowed by concept type, parent, group or subvocabulary. This is a heavy-user feature and nice as such. But for non-heavy-users, the concept type should really be shown already in search results. This is crucial for many domain ontologies in finto.fi since they all include general ontology YSO in them.

**Comment by kinow** [comment]
@tpalonen ah, I think I got it now. So for example, in this search page

http://finto.fi/koko/en/search?clang=fi&q=aall

each result returned would include the Concept Type?

**Comment by tpalonen** [comment]
@kinow precisely. And this search page further explains my point (see the URIs):
http://finto.fi/juho/en/search?clang=fi&q=ilmast&vocabs=

**Comment by kinow** [comment]
Noticed the fields on the left sidebar, indeed not necessity of an advanced search screen.

@tpalonen if you have a test instance maybe you can try this one https://github.com/NatLibFi/Skosmos/compare/master...kinow:display-concepttype-search

Here's what it looks like

![image](https://user-images.githubusercontent.com/304786/41344217-aa038a38-6f54-11e8-9ae8-c7972a43f783.png)

And if that looks good we can wait @henriyli or @osma to review it too, and see if that'd be an interesting feature.

Worked on this one because never used much of search, and also wanted to see how to add translated words :man_dancing: quite simple thanks to the docs! And icon from https://feathericons.com/, with colour changed in Inkscape.

**Comment by osma** [comment]
Wow, I had missed this thread, looks very good @kinow! We'll see whether this could be incorporated in the upcoming 2.0 release.

**Comment by kinow** [comment]
Thanks for reviewing it! I think I didn't create a PR for this one (on mobile now). Should I prepare one??

**Comment by osma** [comment]
@kinow a PR would be great!

**Comment by kinow** [comment]
A fresh PR on its way ! :tada https://github.com/NatLibFi/Skosmos/pull/781
