### ISSUE TITLE
Entry terms display on alphabetical tab

### ISSUE THREAD

**Issue by charlycou** [NatLibFi/Skosmos#798]
Entry terms are not are not displayed for my  vocabulary.
This seems not linked to #614 since UNESCO thesaurus is loaded in the same Apache Jena dataset and display entry terms correctly. 

## At which URL did you encounter the problem?
http://in-situ.theia-land.fr/vocabularies/Skosmos/en/

## What steps will reproduce the problem?
1. go to http://in-situ.theia-land.fr/vocabularies/Skosmos/theia_variables_categories/en/
2. Observ that the entry terms are not displayed

## What is the expected output? What do you see instead?
I expect the following output in alphabetical tab:
_entry term_ -> **preferred term**

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

PLease find below my **vocabularies.ttl**

> :theia_variables_categories a skosmos:Vocabulary, void:Dataset ;
         dc:title "Categories for the variables of Theia in-situ information system"@en ;
         dc:subject :cat_general ;
         void:uriSpace "https://w3id.org/ozcar-theia/" ;
         skosmos:loadExternalResources false ;
         skosmos:language "en";
         skosmos:shortName "Theia in-situ variable categories"@en ;
         skosmos:showTopConcepts true ;
         skosmos:groupClass skos:Collection ;
         void:sparqlEndpoint <http://localhost:3030/theia_vocabulary/sparql> ;
         skosmos:sparqlGraph <https://w3id.org/ozcar-theia/> .
:unesco a skosmos:Vocabulary, void:Dataset ;
        dc:title "UNESCO Thesaurus"@en ;
        skosmos:shortName "UNESCO";
        dc:subject :cat_general ;
        void:uriSpace "http://skos.um.es/unescothes/";
        skosmos:language "en", "es", "fr", "ru";
        skosmos:defaultLanguage "en";
        skosmos:showTopConcepts true ;
        skosmos:groupClass isothes:ConceptGroup ;
        void:sparqlEndpoint <http://localhost:3030/theia_vocabulary/sparql> ;
        skosmos:sparqlGraph <http://skos.um.es/unescothes/> .
:categories a skos:ConceptScheme;
        skos:prefLabel "Skosmos Vocabulary Categories"@en.
:cat_general a skos:Concept ;
        skos:topConceptOf :categories ;
        skos:inScheme :categories ;
        skos:prefLabel "Concepts généraux"@fr,
                "General concepts"@en .
mdrtype:THESAURUS a skos:Concept ;
        skos:prefLabel "Ð¢ÐµÐ·Ð°Ñ<83>Ñ<80>Ñ<83>Ñ<81>"@bg, "Tezaurus"@cs, "Tesaurus"@da, "Thesaurus"@de, "Î<98>Î·Ï<83>Î±Ï<85>Ï<81>Ï<8c>Ï<82>"@el, "Thesaurus"@en, "Tesaurus"@et, "Tesaurus"@fi, "ThÃ©saurus"@fr, "Pojmovnik"@hr, "Tezaurusz"@hu, "Tesauro"@it, "TÄ<93>zaurs"@lv, "Tezauras"@lt, "TeÅ¼awru"@mt, "Thesaurus"@nl, "Tesaurus"@no, "Tezaurus"@pl, "Tesauro"@pt, "Tezaur"@ro, "SynonymickÃ½ slovnÃ­k"@sk, "Tezaver"@sl, 
"Tesauro"@es,
 "Tesaurus"@sv .
mdrtype:ONTOLOGY a skos:Concept ;
    skos:prefLabel "Ð<9e>Ð½Ñ<82>Ð¾Ð»Ð¾Ð³Ð¸Ñ<8f>"@bg, "Ontologie"@cs, "Ontologi"@da, "Ontologie"@de, "Î<9f>Î½Ï<84>Î¿Î»Î¿Î³Î¯Î±"@el, "Ontology"@en, "Ontoloogia"@et, "Ontologia"@fi, "Ontologie"@fr, "Ontologija"@@@@

**Comment by kouralex** [comment]
It seems like you have multiple concepts with the same skos:prefLabel, is this intended? I believe that Skosmos was not designed for this kind of user case, though, it should be possible to support a use case like this (at least in alphabetical view).

Entry terms (skos:altLabel) in the alphabetical view are shown only if they match (i.e., start with) the character selected. In case both skos:altLabel and skos:prefLabel start with the same character, both are shown in separate rows. Please note that for other views only skos:prefLabel is used, which in your use case will cause trouble if one wants to differentiate the concept from similarly named concepts.

In some other vocabularies this issue is circumvented via the usage of qualifiers, e.g., adding a qualifier for the concept in parenthesis after the "main" term. See for example (https://finto.fi/yso/en/page/p30025) and (https://finto.fi/yso/en/page/p29920). If possible, I would suggest adding some kind of a quantifier to every homophone.

And to conclude, entry terms for your vocabulary are working as is; see (http://in-situ.theia-land.fr/vocabularies/Skosmos/theia_variables_categories/en/index/K) for example.

**Comment by charlycou** [comment]
The homophones are intended. My first thought was to use skos:altLablel to differentiate them on Skosmos interface. Qualifier usage seems to be a better practice and I will move toward this solution. 

Thank you for your support.
