### ISSUE TITLE
Group hierarchy doesn't show concept members if the group has other groups as members

### ISSUE THREAD

**Issue by frosterus** [NatLibFi/Skosmos#810]
## At which URL did you encounter the problem?
http://dev.finto.fi/mts/en/page/m100000

## What steps will reproduce the problem?
Go to the groups tab and navigate to "henkilö" and then to "ammatti tai tehtävä"

## What is the expected output? What do you see instead?
You see only three groups as members of the group even though it has a lot of concepts as members as well. If you open a group (e.g. "ohjaaja (kasvatus ja opastus)") then you will the member concepts as it does not have a member group.

The Group hierarchy should always show both group members and concept members.

**Comment by kouralex** [comment]
This has proven to be quite difficult to solve. Possible resolutions are:

1) Create a new REST API method or update the already existing "groups" method to return member concepts for groups

2) Call REST API method "groupMembers" recursively (via separate "groupMembers" API calls) in /resource/js/groups.js to find out concept members for each group needed (i.e., traverse the group tree upwards)

3) Create a new REST API method that returns the concept members for required groups

Resolution 1) is quite heavy - for large vocabularies it may take more than 20 seconds to return the whole hierarchy which is not acceptable in general (could work for caching Skosmos installations, though)

Resolution 2) causes lots of requests to be sent to API/endpoint and we should not show the tree before all are solved.

Resolution 3) would be the greatest method of all IMHO since it provides the most optimal resolution to this question. It should be quite possible to create such a SPARQL query that efficiently returns the required info and nothing else.

One of the problems is that tackling this issue requires some in-depth knowledge and manipulation of the data structure of the [jQuery tree plugin jsTree](https://www.jstree.com/) (which is used for showing the hierarchy) if resolutions 1 or 2 are applied (actually, for resolution 3, too).

Anyways, I think this issue requires a bit of discussion before implementing.

**Comment by kouralex** [comment]
Duplicate issue of #620 , related to #366

**Comment by osma** [comment]
I think that resolution 1 is a non-starter because it would take a long time to get the whole tree (e.g. for YSO it would return all 30k concepts) and only a small part of the tree would actually be needed by the jsTree widget for any particular page.

Resolution 2 seems ideal to me. The group hierarchy is unlikely to be very deep (seldom more than 4 levels) and the results for the upper levels would be cached on several levels - I think jsTree itself maintains a cache (as long as the browser stays on the same page), the browser itself has a HTTP cache, and on the server side there is likely a Varnish or similar cache.

I don't like resolution 3, because the method would be called with slightly different parameters each time so none of the results would be cached anywhere.

I think we should try out resolution 2 first and if there are performance or other issues, try to resolve them as they come up.

**Comment by osma** [comment]
I think that resolution 1 is a non-starter because it would take a long time to get the whole tree (e.g. for YSO it would return all 30k concepts) and only a small part of the tree would actually be needed by the jsTree widget for any particular page.

Resolution 2 seems ideal to me. The group hierarchy is unlikely to be very deep (seldom more than 4 levels) and the results for the upper levels would be cached on several levels - I think jsTree itself maintains a cache (as long as the browser stays on the same page), the browser itself has a HTTP cache, and on the server side there is likely a Varnish or similar cache.

I don't like resolution 3, because the method would be called with slightly different parameters each time so none of the results would be cached anywhere.

I think we should try out resolution 2 first and if there are performance or other issues, try to resolve them as they come up.

(resending comment that appears to have been lost)

**Comment by osma** [comment]
Test comment. Apparently GitHub has some database issues.

**Comment by osma** [comment]
Test comment. Apparently GitHub has some database issues.

**Comment by kouralex** [comment]
Dropping this from the upcoming 2.2 release. The issue persists but is no more acute to us as the modeling was fixed in the MTS vocabulary.

**Comment by kouralex** [comment]
The modeling of MTS once again requires this issue to be tackled. Hence, I am moving this back to the Next Tasks milestone.
