### ISSUE TITLE
Long prefLabels can overlap GUI elements

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#857]
## At which URL did you encounter the problem?
http://dev.finto.fi/hero/fi/page/p3241

## What is the expected output? What do you see instead?
The layout for labels and for the breadcrumb line above it should be reconsidered in cases where an additional image is located at the end of the lines so that long lines don't overlap the image.

The space on the first few lines should be reserved for the label and the horizontal hierarchy list. Images located in the top-right area of the concept view should be shifted down a bit. There might still be a need for wrapping the text of an exceptionally long prefLabel to an additional line.

**Comment by joelit** [comment]
It seems the breadcrumbs can also push the pref label out of its container:
http://finto.fi/ysa/en/page/Y101586

**Comment by kouralex** [comment]
I am closing this issue since Hero ontology is using the following [plugin](https://github.com/henriyli/skosmos-widget-hero) as a very simple implementation that does not currently take into consideration the raised issue. I believe it should be fixed in the plugin, not in the Skosmos code. In case you think such (optional) feature should be supported in the Skosmos software, feel free to open a new issue.

For the second comment, the YSA ontology link you provided did not cause any issues in my case, so it might be browser-related? Anyway, a replicable example is needed.
