### ISSUE TITLE
RestController doesn't handle content language

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#882]
While WebController uses content language as its parameter, the functionality is missing from RestController, probably by accident. This caused some issues when getting external labels through mappings function.

## At which URL did you encounter the problem?
http://api.dev.finto.fi/rest/v1/yso-paikat/mappings?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp94080&clang=fi

Even though trying to set the content language with 'clang', the wikidata link is returned in a rangom language, this case in Greek.

**Comment by osma** [comment]
I don't think this is a problem. In the REST API, the "lang" parameter actually specifies the content language, because there's no UI in REST. I know this isn't entirely consistent with the URL parameters of the UI, but that's because the REST API was created before the separation of UI vs content language. In any case, I don't think there is a need for a separate "clang" parameter in the REST API.

**Comment by osma** [comment]
The original reported problem (getting a random language for the wikidata link) is of course a valid issue but I think it can be solved without introducing a clang parameter in the REST API, simply by making sure the lang parameter gets passed correctly.
