### ISSUE TITLE
Labels are displayed in every language

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#957]
## What steps will reproduce the problem?
1. Go to the front page of some vocabulary, e.g. YSO
2. The alphabetical list on the right shows the same concepts several times, these would be the prefLabel in fi, sv and en:
![image](https://user-images.githubusercontent.com/578627/76832338-d1288000-6831-11ea-83d3-de70f9c4b2fb.png)
3. The drop-down search displays the label for every matching language:
![image](https://user-images.githubusercontent.com/578627/76832440-fc12d400-6831-11ea-92fd-834bed3a7496.png)

## What is the expected output? What do you see instead?
Each concept should be displayed once with its suitable label.

It seems that the language parameter is passed incorrectly for the alphabetical listing and the drop-down search results, which means the results are matched in every language.

**Comment by osma** [comment]
The second problem (search autocomplete) is caused by a case mismatch on [this line](https://github.com/NatLibFi/Skosmos/blob/master/model/sparql/JenaTextSparql.php#L56). The variable is defined in the surrounding query as `?langParam` but the all-lowercase `?langparam` is used here. It is always unbound so doesn't restrict languages.
